config/routes.rb
Rails.application.routes.draw do
  get '/sign_out_user', to: 'users#sign_out_user', as: 'sign_out_user'
  devise_for :users
  get 'comments/new'
  get 'comments/create'
  get 'likes/new'
  get 'likes/create'
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
        resources :likes, only: [:new, :create]
      end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_post_comments_counter

  private

  def update_post_comments_counter
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_post_likes_counter

  private

  def update_post_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_user_posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_user_posts_counter
    author.update(posts_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: :author_id
  has_many :comments
  has_many :likes

  validates :name, presence: true
  validates :photo, presence: true
  validates :bio, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :email, :bio, :photo, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :bio, :photo, :password, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @post = Post.find(params[:post_id])
    # @comment.author_id = current_user.id
    @comment.author = User.find(params[:user_id])
    @comment.post_id = @post.id

    if @comment.save
      redirect_to user_post_path(user_id: @post.author, id: @post.id)
    else
      flash[:alert] = 'An error has occurred while creating the comment'
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @post = Post.find(params[:post_id])
    @like = Like.new(author_id: current_user.id, post_id: @post.id)
    if @like.save
      redirect_to user_post_path(user_id: @post.author_id, id: @post.id)
    else
      flash[:alert] = 'Can not add new like'
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # index action displaying a list of posts belonging to a specific user
  # first retrieves the user record base on user_id
  # next fetches all posts associated with that user using @user.posts

  def index
    @user = User.find(params[:user_id])
    # @posts = @user.posts
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = User.find(params[:user_id])

    if @post.save
      flash[:notice] = 'Post created successfully!'
      redirect_to user_posts_path(id: @post.id)
    else
      flash[:alert] = 'Cannot create a new post'
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # The index action is responsible for displaying a list of users. It fetches all user records from the database
  # assigns them to an instance variable @users.
  # This instance variable can be accessed within the corresponding view file to display the list of users.
  def index
    @users = User.all
  end

  # the show action retrieves a user record from the database
  # based on the id parameter passed in the request (params[:id]).
  def show
    @user = User.find(params[:id])
  end

  def sign_out_user
    sign_out(current_user)
    redirect_to root_path, notice: 'Signed out successfully'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<section class="new-post-section">
<div class="new-post-container">
        <h1>Add a new comment</h1>
<%= form_with model: @comment, url: user_post_comments_path do |c| %>
<div class="text-container">
     <%= c.label :text%>
    <%= c.text_area :text, cols: 30, rows:1%><br>
</div>

    <%= c.submit "Submit", class:"new-post-btn submit-btn" %>
<% end %>
</div>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
   <style>
      .flash {
        padding: 10px;
        margin-bottom: 10px;
        border-radius: 5px;
      }

      .flash-notice {
        background-color: #e6f7ff;
        color: #007bff;
      }

      .flash-alert {
        background-color: #ffe6e6;
        color: #dc3545;
      }
    </style>
  <body>
  <%# key represents the type of flash message (e.g., notice, alert, etc.), 
  and the value represents the actual message content. %>
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/partials/_user.html.erb
<%# Partials allow you to break down complex views into smaller %>
<%# reuse view code across different views or layouts %>
<%# This partial can be rendered in different views %>
<%# user is a local variable used within the partial to represent an individual user object during iteration %>
<%= link_to user do%>
<li class="user-card">
   <div class ="user-img">
     <img src= <%= user.photo%> class="user-photo">
   </div>
   <div class="user-info">
      <h2><%= user.name%></h2>
      <h2 class="post-counter"> Number of posts: <%= user.posts_counter%></h2>
     
   </div>
</li>
<% end %>

app/views/posts/index.html.erb
<h1 class="post-title"><%= @user.name%>'s Posts</h1>
  <div class="user-card-container">
   <div class="user-card" >
        <div class="user-img">
            <img src=<%= @user.photo %> width="100px"  height = "100px" class="user-photo">
        </div>
        <div class="user-info">
            <h2><%= @user.name %></h2>
            <h2 class="post-counter">Number of posts: <%= @user.posts_counter %></h2>
        </div>
    </div>
          <%= link_to "Add a new post", new_user_post_path(user_id: @user.id), class: "new-post-btn post-btn"%>
  </div>

<div class="post-container">
    <% @posts.each do |post|%>
    <%= link_to user_post_path(user_id: post.author_id, id: post.id) do%>
        <div class="post-card-container">
             <div class="post-card">
                <h2><%= post.title %></h2>
                <p><%= post.text %></p>
                <div class="reactions">
                    <span>Comments <%= post.comments_counter%> </span>
                    <span>Likes <%= post.likes_counter%> </span>
                </div>
            </div>
            <h4 class="comment-title">Comments</h4>
            <div class="comment-container">
                <% post.recent_comments.each do |comment|%>
                    <span><%= comment.author.name%> : <%= comment.text%></span>
                <% end %>
            </div>
        </div>
         
        <% end %>
    <% end %>
 <div>
     <a class='pagination-btn' href='#'>Pagination</a>
</div>
</div>

app/views/posts/new.html.erb
<section class="new-post-section">
  <div class="new-post-container">
       <h1>Add a new post</h1>
       <%= form_with model:@post, url:user_posts_path do |form|%>
        <%= form.label :title%>
        <%= form.text_field  :title%><br>

        <div class="text-container">
          <%= form.label :text%>
           <%= form.text_area :text, cols:40, row:1%>
        </div>

        <%=form.submit "Submit", class:"new-post-btn submit-btn"%>
     <% end%>
  </div>

</section>

app/views/posts/show.html.erb
<div class="post-container">
   <div class="post-header">
       <h2><%= @post.title%> By <%= @post.author.name%></h2>
         <ul>
             <li>Comments:<%= @post.comments_counter%></li>
             <li>Likes:<%=@post.likes_counter%></li>
         </ul>
   </div>
   
    <h4 class="comment-title"> Comments</h4>
    <div class="post-body">
       <%=@post.text%>
    </div>

     <div class="comment-container">
        <%@post.comments.each do |comment|%>
          <span> <%= comment.author.name%> :<%= comment.text%></span>
          <%end%>
     </div>

        <div class="like-comment-container">
            <%= form_with model: @like, url:user_post_likes_path(post_id: @post.id) do |l| %>
                <%= l.submit  "Like", class:"new-post-btn submit-btn"%>
            <% end %>
            <%= link_to "Add a comment", new_user_post_comment_path(user_id: @post.author.id, post_id: @post.id), class: 'new-post-btn submit-btn' %>
    </div>
</div>

app/views/users/index.html.erb
<%# The render method is used to render the partials/user partial for each user object in the @users collection. %>
<%# The render method automatically assigns each element of the collection to a local variable within the partial. %>
<%# @users is an instance variable that typically holds a collection of user objects. %>

<div class = " flex justify-center items-center">
    <h1 class="user-title font-bold text-4xl my-10 me-4"> Welcome To User Page</h1>
<%= link_to "Log Out", sign_out_user_path %>
</div>

<div class="user-container">
  <ul>
    <%= render partial:'partials/user', collection:@users%>  
  </ul>
</div>

app/views/users/show.html.erb
 <section class="user-section">
    <div class="user-card" >
        <div class="user-img">
            <img src=<%= @user.photo %> width="100px"  height = "100px" class="user-photo">
        </div>
        <div class="user-info">
            <h2><%= @user.name %></h2>
            <h2 class="post-counter">Number of posts: <%= @user.posts_counter %></h2>
        </div>
    </div>

     <div class="bio-container">
        <h2>Bio</h2>
        <p><%=  @user.bio%></p>
     </div>
 </section>
 <section class="post-section">
    <div class="post-container">
        <% @user.recent_posts.each do |post|%>
            <div class="post-card">
                <h2><%= link_to post.title, user_post_path(@user, post) %></h2>
                <p><%= post.text %></p>
                <div class="reactions">
                    <span>Comments <%= post.comments_counter%> </span>
                    <span>Likes <%= post.likes_counter%> </span>
                </div>
            </div>
        <% end%>
    </div>
    <%= link_to "See all posts", user_posts_path(user_id: @user.id), class: "all-post" %>
 </section>
 